language: python
python:
- '3.5'
addons:
  ssh_known_hosts: fomalhaut.me
before_install:
- bash .travis/before-install.sh
install:
- pip install -e .
- pip install -e '.[testing]'
services: mongodb
env:
- HEL_TESTING_MONGODB_ADDR='mongodb://localhost:27017'
script: py.test
after_success:
- bash .travis/deploy.sh
- echo Done!
notifications:
  irc:
    channels:
    - irc.esper.net#cc.ru
    use_notice: true
    template:
    - "\x02%{repository_name}#%{build_number}\x02 [\x1F%{branch}\x1F] \x1F%{message}"
    - "\x02Elapsed time:\x02 %{elapsed_time} | \x02Total duration:\x02 %{duration}"
    - "\x02Build details:\x02 %{build_url}"
